// <auto-generated />
using System;
using LifeFit.Dominio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeFit.Dominio.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251125004247_Colocando-nome-e-focomuscular-nome-na-sugestao")]
    partial class Colocandonomeefocomuscularnomenasugestao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeFit.Dominio.Entidades.Exercicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Enum")
                        .HasColumnType("integer");

                    b.Property<int>("FocoMuscular")
                        .HasColumnType("integer");

                    b.Property<string>("FocoMuscularNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("sugestaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("sugestaoId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.PerfilUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Foco")
                        .HasColumnType("integer");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<int>("NivelAtividadeFisica")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Objetivo")
                        .HasColumnType("integer");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PerfisUsuarios");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.RequisicaoSugestao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoRetorno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocoMuscular")
                        .HasColumnType("integer");

                    b.Property<long>("PerfilUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerfilUsuarioId");

                    b.ToTable("RequisicoesSugestao");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.Sugestao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExercicioId")
                        .HasColumnType("bigint");

                    b.Property<string>("FocoMuscular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeExercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PerfilUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("PontosPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("RequisicaoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("PerfilUsuarioId");

                    b.HasIndex("RequisicaoId");

                    b.ToTable("Sugestoes");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.Feedback", b =>
                {
                    b.HasOne("LifeFit.Dominio.Entidades.Sugestao", "sugestao")
                        .WithMany()
                        .HasForeignKey("sugestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sugestao");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.RequisicaoSugestao", b =>
                {
                    b.HasOne("LifeFit.Dominio.Entidades.PerfilUsuario", "PerfilUsuario")
                        .WithMany()
                        .HasForeignKey("PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilUsuario");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.Sugestao", b =>
                {
                    b.HasOne("LifeFit.Dominio.Entidades.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeFit.Dominio.Entidades.PerfilUsuario", "PerfilUsuario")
                        .WithMany()
                        .HasForeignKey("PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeFit.Dominio.Entidades.RequisicaoSugestao", "Requisicao")
                        .WithMany("Sugestoes")
                        .HasForeignKey("RequisicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("PerfilUsuario");

                    b.Navigation("Requisicao");
                });

            modelBuilder.Entity("LifeFit.Dominio.Entidades.RequisicaoSugestao", b =>
                {
                    b.Navigation("Sugestoes");
                });
#pragma warning restore 612, 618
        }
    }
}
